# -*- coding: utf-8 -*-
# Global HTML attributes — can be used on ANY element.
# Source: MDN/W3Schools HTML Global Attributes, cross-checked with the references.

GLOBAL_ATTRS = [
    ("accesskey", "A keyboard shortcut (single character) that focuses/activates the element, e.g. accesskey=\"s\" → Alt+S (Windows) / Ctrl-Option-S (macOS). Use sparingly — they collide with browser shortcuts.", "accesskey=\"s\""),
    ("class", "One or more space-separated class names. The backbone of CSS styling and JS queries: <p class=\"card dark\">. Multiple classes: class=\"a b c\".", "class=\"hero primary\""),
    ("contenteditable", "Makes the element's content editable in place. true / false / plaintext-only. The browser shows a plain text-editing UI.", "contenteditable=\"true\""),
    ("data-…", "Custom data-* attributes for your own scripts. Must start with a letter, no uppercase. Read with el.dataset.name (camelCase).", "data-id=\"42\""),
    ("dir", "Forces text direction: ltr (left-to-right), rtl (right-to-left), or auto (detect from content). Useful for user-generated names/quotes.", "dir=\"rtl\""),
    ("draggable", "Whether the element can be dragged (HTML5 Drag & Drop API). true / false. Default true for images and links.", "draggable=\"true\""),
    ("hidden", "Removes the element from rendering (display:none). Can be overridden by CSS. Browsers respect it even before CSS loads — a11y-safe hiding.", "hidden"),
    ("inert", "The element and its descendants are non-interactive and invisible to assistive technology (greyed out). Great for disabling sidebars while a modal is open.", "inert"),
    ("inputmode", "Hint for the mobile virtual keyboard: none, text, search, tel, url, email, numeric, decimal, telephone. No effect on desktop.", "inputmode=\"numeric\""),
    ("is", "The name of a custom element to upgrade this built-in element to (tagged custom elements, e.g. <article is=\"my-card\">).", "is=\"my-card\""),
    ("itemid", "Part of (the deprecated) microdata: a unique identifier for an item.", "itemid=\"urn:book:1\""),
    ("itemprop", "Microdata: the property name of an item (e.g. itemprop=\"name\").", "itemprop=\"price\""),
    ("itemscope", "Microdata: makes this element the scope of a new item.", "itemscope"),
    ("itemtype", "Microdata: the URL of the schema the item follows.", "itemtype=\"https://schema.org/Book\""),
    ("lang", "The language of the element's content (BCP-47). Used by screen readers to switch pronunciation and by spellcheckers. Inheritable.", "lang=\"ar\""),
    ("nonce", "A cryptographic nonce used with Content Security Policy to allow specific inline scripts/styles.", "nonce=\"abc123\""),
    ("part", "CSS Part API: exposes a part of the element to ::part() styling from outside a shadow DOM.", "part=\"label icon\""),
    ("popover", "Makes the element a native popover: auto or hint. Toggled with element.showPopover().", "popover"),
    ("role", "ARIA: overrides/declares the accessible role (e.g. role=\"alert\", role=\"presentation\"). Prefer native elements first.", "role=\"status\""),
    ("slot", "Assigns the element to a named <slot> in a shadow DOM template.", "slot=\"header\""),
    ("spellcheck", "Whether spellcheck applies: true / false. Inheritable — set it once on <html>.", "spellcheck=\"false\""),
    ("style", "Inline CSS declarations for this one element. Prefer classes; use for dynamic values only.", "style=\"color: teal\""),
    ("tabindex", "Controls keyboard focus order: 0 = focusable in DOM order, positive = custom order (avoid), -1 = focusable via JS only (not by Tab).", "tabindex=\"0\""),
    ("title", "Advisory tooltip text on hover. A fallback, not an information channel — important info must be visible.", "title=\"Copy to clipboard\""),
    ("translate", "Whether machine translation applies: yes / no. Use no on brand names and code.", "translate=\"no\""),
    ("autocapitalize", "Mobile keyboards: off / sentences / words / characters — auto-capitalization behavior.", "autocapitalize=\"off\""),
    ("autofocus", "Focus this element when the page loads. At most one per page; can hurt mobile/keyboard UX if abused.", "autofocus"),
    ("checked", "Default state of checkboxes/radios (HTML-only; change with JS .checked).", "checked"),
    ("disabled", "Disables a form control: not clickable, not submitted, greyed by default.", "disabled"),
    ("readonly", "A form control is selectable but cannot be edited; its value still submits.", "readonly"),
    ("required", "The control must have a valid value before the form can submit (native validation).", "required"),
    ("selected", "Pre-selects an <option> in a <select> (HTML default state).", "selected"),
    ("value", "The current value of inputs/outputs: text, number, date, file…", "value=\"25\""),
    ("name", "The submitted key for form controls (and radios group by name).", "name=\"email\""),
    ("id", "A unique identifier within the document — used by CSS #id, href=\"#id\", for=, and getElementById. Must be unique per page.", "id=\"hero\""),
    ("aria-…", "Any ARIA attribute (aria-label, aria-expanded, aria-hidden, aria-live…) adds accessibility semantics when native HTML is not enough.", "aria-expanded=\"true\""),
]
